# Introducción a Pandas, Matplotlib y Streamlit

### ¿Qué aprenderemos hoy?

* Leer datos desde un archivo CSV 📄
* Explorar y limpiar datos con Pandas 🐼
* Crear gráficos simples con Matplotlib 📊
* Mostrar un dashboard interactivo usando Streamlit 🚀

### Requerimientos: 
1. Datasets
2. Librerias: Pandas, Matplotlib y Streamlit(Este ultimo es para mostrar una interfaz con pocas lineas de código).

Para realizar esto, debemos instalar las siguientes dependencias

In [1]:
pip install pandas matplotlib streamlit

Collecting pandas
  Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting streamlit
  Using cached streamlit-1.44.1-py3-none-any.whl.metadata (8.9 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.2.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ipf-2024\onedrive\documentos\delitos_bigdata\.env\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.2-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.57.0-cp313-cp313-win_amd64.whl.metadata (104 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\ipf-2024\onedrive\documentos\delitos_bigdata\.env\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.2.1-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting altair<6,>=4.0 (from streamlit)
  Using cached altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.0.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<6,>=4.0 (from streamlit)
  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting click<9,>=7.0 (from streamlit)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting packaging>=20.0 (from matplotlib)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting protobuf<6,>=3.20 (from streamlit)
  Using cached protobuf-5.29.4-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Using cached pyarrow-19.0.1-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Collecting requests<3,>=2.27 (from streamlit)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions<5,>=4.4.0 (from streamlit)
  Using cached typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Using cached GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\ipf-2024\onedrive\documentos\delitos_bigdata\.env\lib\site-packages (from streamlit) (6.4.2)
Collecting jinja2 (from altair<6,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair<6,>=4.0->streamlit)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)
  Using cached narwhals-1.36.0-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: colorama in c:\users\ipf-2024\onedrive\documentos\delitos_bigdata\.env\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\ipf-2024\onedrive\documentos\delitos_bigdata\.env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.27->streamlit)
  Using cached charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.27->streamlit)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.27->streamlit)
  Using cached urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.27->streamlit)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair<6,>=4.0->streamlit)
  Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached rpds_py-0.24.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
Using cached matplotlib-3.10.1-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached streamlit-1.44.1-py3-none-any.whl (9.8 MB)
Using cached altair-5.5.0-py3-none-any.whl (731 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached cachetools-5.5.2-py3-none-any.whl (10 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached contourpy-1.3.2-cp313-cp313-win_amd64.whl (223 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.57.0-cp313-cp313-win_amd64.whl (2.2 MB)
Using cached GitPython-3.1.44-py3-none-any.whl (207 kB)
Using cached kiwisolver-1.4.8-cp313-cp313-win_amd64.whl (71 kB)
Using cached numpy-2.2.5-cp313-cp313-win_amd64.whl (12.6 MB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached pillow-11.2.1-cp313-cp313-win_amd64.whl (2.7 MB)
Using cached protobuf-5.29.4-cp310-abi3-win_amd64.whl (434 kB)
Using cached pyarrow-19.0.1-cp313-cp313-win_amd64.whl (25.2 MB)
Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached typing_extensions-4.13.2-py3-none-any.whl (45 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl (102 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
Using cached narwhals-1.36.0-py3-none-any.whl (331 kB)
Using cached urllib3-2.4.0-py3-none-any.whl (128 kB)
Using cached attrs-25.3.0-py3-none-any.whl (63 kB)
Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl (18 kB)
Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl (15 kB)
Using cached referencing-0.36.2-py3-none-any.whl (26 kB)
Using cached rpds_py-0.24.0-cp313-cp313-win_amd64.whl (239 kB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Installing collected packages: pytz, watchdog, urllib3, tzdata, typing-extensions, toml, tenacity, smmap, rpds-py, pyparsing, pyarrow, protobuf, pillow, packaging, numpy, narwhals, MarkupSafe, kiwisolver, idna, fonttools, cycler, click, charset-normalizer, certifi, cachetools, blinker, attrs, requests, referencing, pandas, jinja2, gitdb, contourpy, pydeck, matplotlib, jsonschema-specifications, gitpython, jsonschema, altair, streamlit
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
Successfully installed MarkupSafe-3.0.2 altair-5.5.0 attrs-25.3.0 blinker-1.9.0 cachetools-5.5.2 certifi-2025.1.31 charset-normalizer-3.4.1 click-8.1.8 contourpy-1.3.2 cycler-0.12.1 fonttools-4.57.0 gitdb-4.0.12 gitpython-3.1.44 idna-3.10 jinja2-3.1.6 jsonschema-4.23.0 jsonschema-specifications-2025.4.1 kiwisolver-1.4.8 matplotlib-3.10.1 narwhals-1.36.0 numpy-2.2.5 packaging-24.2 pandas-2.2.3 pillow-11.2.1 protobuf-5.29.4 pyarrow-19.0.1 pydeck-0.9.1 pyparsing-3.2.3 pytz-2025.2 referencing-0.36.2 requests-2.32.3 rpds-py-0.24.0 smmap-5.0.2 streamlit-1.44.1 tenacity-9.1.2 toml-0.10.2 typing-extensions-4.13.2 tzdata-2025.2 urllib3-2.4.0 watchdog-6.0.0
Note: you may need to restart the kernel to use updated packages.

## Extración de datos con Pandas
Ahora que ya tenemos nuestro datasets, vamos a utilizar pandas para leer nuestro csv

**Importamos pandas y le asignamos el alias pd (por convencion, siempre se utiliza pd al importar)**

* `import pandas as pd`

In [4]:
import pandas as pd

Ahora utilizaremos el metodo `pd.read_pdf(nombre_csv)` para leer el datasets y lo guardaremos en una variable llamada df(DataFrame)

In [5]:
# import pandas as pd
# import os

# def convertir_excel_a_csv(año_inicio, año_fin, combinar=True):
#     """
#     Convierte archivos Excel de delitos a CSV para un rango de años y opcionalmente los combina.
    
#     Args:
#         año_inicio: Año inicial (ej: 2019)
#         año_fin: Año final (ej: 2023)
#         combinar: Si es True, combina todos los CSVs en un solo archivo
#     """
#     # Lista para almacenar DataFrames si vamos a combinar
#     dfs = []
    
#     # Procesar cada año en el rango
#     for año in range(año_inicio, año_fin + 1):
#         archivo_excel = f'delitos_{año}.xlsx'
#         archivo_csv = f'delitos_{año}.csv'
        
#         try:
#             # Leer el archivo Excel
#             print(f"Procesando {archivo_excel}...")
#             df = pd.read_excel(archivo_excel)
            
#             # Verificar si ya existe columna 'anio', si no, añadirla
#             if 'anio' not in df.columns:
#                 df['anio'] = año
            
#             # Guardar como CSV
#             df.to_csv(archivo_csv, index=False, sep=',', encoding='utf-8')
#             print(f"✅ Archivo CSV {archivo_csv} guardado correctamente")
            
#             # Añadir a la lista para combinar después
#             if combinar:
#                 dfs.append(df)
                
#         except FileNotFoundError:
#             print(f"❌ El archivo {archivo_excel} no se encontró")
#         except Exception as e:
#             print(f"❌ Error al procesar {archivo_excel}: {str(e)}")
    
#     # Combinar todos los archivos en uno solo si se solicitó
#     if combinar and dfs:
#         archivo_combinado = f"delitos_{año_inicio}_{año_fin}.csv"
#         df_combinado = pd.concat(dfs, ignore_index=True)
#         df_combinado.to_csv(archivo_combinado, index=False, sep=',', encoding='utf-8')
#         print(f"🔄 Se ha creado el archivo combinado {archivo_combinado} con {len(df_combinado)} registros")
#         return df_combinado
    
#     return None
# convertir_excel_a_csv(2019, 2023, combinar=True)

df = pd.read_csv("delitos_2019_2023.csv")
df.head()

# df = pd.read_csv("delitos_2016_2023.csv")
# df.head()

C:\Users\IPF-2024\AppData\Local\Temp\ipykernel_21832\761756397.py:54: DtypeWarning: Columns (11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("delitos_2019_2023.csv")

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,252569,2019,enero,LUN,2019-01-28,8.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630835.0,-58391528.0,1
1,252570,2019,marzo,LUN,2019-03-04,11.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34628442.0,-58391876.0,1
2,252571,2019,abril,MIE,2019-04-10,18.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34630313.0,-58391512.0,1
3,252572,2019,noviembre,LUN,2019-11-18,12.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630163.0,-58391542.0,1
4,252573,2019,abril,LUN,2019-04-01,17.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34629944.0,-58391882.0,1

### Exploracion de datos:
Una vez creado el df, podemos utilizar metodos de pandas que nos ayudaran a observar mejor los datos.
En este caso, utilizaremos las funciones: 

* `df.shape()` <- Obtener cuantas columnas y filas tiene el df.
* `df.colums` <- Obtener el nombre de las columnas.
* `df.dtypes` <- Obtener los tipos dedatos de cada columna.
* `df.info()` <- Obtener una vista rapida de los tipos de datos del df.
* `df.isnull().sum()` <- Obtener la cantidad de datos nulos en nuestro df.

In [10]:
#utilizamos el metodo shape para obtener las dimensiones del dataframe
print(df.shape)

#utilizamos el metodo columns para obtener los nombres de las columnas
print(df.columns)

#utilizamos el metodo dtypes para obtener los tipos de datos de cada columna
print(df.dtypes)

(1097145, 14)
Index(['anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo', 'uso_arma',
       'uso_moto', 'barrio', 'comuna', 'latitud', 'longitud', 'cantidad'],
      dtype='object')
anio                 int64
mes                 object
dia                 object
fecha       datetime64[ns]
franja             float64
tipo                object
subtipo             object
uso_arma            object
uso_moto            object
barrio              object
comuna              object
latitud             object
longitud            object
cantidad             int64
dtype: object

In [7]:
#utilizamos el metodo info para obtener un resumen del dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 997295 entries, 0 to 1097144
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   anio            997295 non-null  int64
 1   mes             997295 non-null  object
 2   dia             997295 non-null  object
 3   fecha           997295 non-null  object
 4   franja          997295 non-null  float64
 5   tipo            997295 non-null  object
 6   subtipo         997295 non-null  object
 7   uso_arma        997295 non-null  object
 8   uso_moto        997295 non-null  object
 9   barrio          997295 non-null  object
 10  comuna          997295 non-null  object
 11  latitud         997295 non-null  float64
 12  longitud        997295 non-null  float64
 13  cantidad        997295 non-null  int64
 14  dia_semana_num  997295 non-null  float64
 15  tipo_dia        997295 non-null  object
 16  trimestre       997295 non-null  float64
 17  latitud_norm    997295 non-null  float64
 18  longitud_norm   997295 non-null  float64
dtypes: float64(7), int64(2), object(10)
memory usage: 152.2+ MB
None

Ahora utilizaremos el metodo `isnull()` para ver si hay valores nulos en el dataframe y esto lo potenciamos con el metodo `sum()` para ver la cantidad de valores nulos por columna

In [6]:

print(df.isnull().sum())

id-mapa         0
anio            0
mes             0
dia             0
fecha           0
franja       2313
tipo            0
subtipo         0
uso_arma        0
uso_moto        0
barrio       9116
comuna       9102
latitud     11238
longitud    11238
cantidad        0
dtype: int64

### Limpieza de datos.
Con el metodo anterior vimos que tenemos datos faltantes en nuestro df, esto podria afectar negativamente a nuestras estadisticas, por lo tanto, debemos limpiarlos. Para ello, vamos a utilizar los siguientes metodos: 

* `df.fillna(0, inplace=True)`: Este es un método que se aplica al DataFrame df. Su propósito es llenar los valores que faltan.

1. 0: Este es el valor que se utilizará para reemplazar todos los valores faltantes (NaN) encontrados en el DataFrame. En este caso, todos los NaN serán sustituidos por el número cero.

2. inplace=True: Este es un argumento booleano (True o False).

Si se establece en True, la modificación se realiza directamente sobre el DataFrame original df. Esto significa que el DataFrame df se actualizará con los valores faltantes reemplazados, y la función fillna() no devolverá un nuevo DataFrame.
Si se omitiera este argumento o se estableciera en False (que es el valor predeterminado), fillna() devolvería un nuevo DataFrame con los valores faltantes reemplazados, dejando el DataFrame original sin modificar. En este caso, para guardar los cambios, tendrías que asignar el resultado a una nueva variable o sobrescribir la variable original (por ejemplo, df = df.fillna(0)).

In [7]:
df.fillna(0, inplace=True)
df.isnull()

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646035,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
646036,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
646037,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
646038,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
646039,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

Reemplazamos los datos NaN por 0, pero esto no es lo ideal, ya que si tenemos un NaN en una columna de tipo string, no podemos reemplazarlo por 0. Por lo tanto, vamos a eliminar las filas que tengan datos nulos. Para ello utilizamos el siguiente metodo:
* `df.dropna(inplace=True)`: Este método se utiliza para eliminar filas o columnas que contienen valores nulos (NaN) en un DataFrame de pandas.

In [8]:
df.dropna(inplace=True)
df.isnull().sum()

id-mapa     0
anio        0
mes         0
dia         0
fecha       0
franja      0
tipo        0
subtipo     0
uso_arma    0
uso_moto    0
barrio      0
comuna      0
latitud     0
longitud    0
cantidad    0
dtype: int64

Con el argumento `inplace=True`, se indica que la operación debe realizarse directamente sobre el DataFrame original, modificándolo en su lugar. Esto significa que las filas o columnas con valores nulos serán eliminadas del DataFrame df y no se creará una copia del DataFrame sin los valores nulos.

Tambien, podemos eliminar columnas que por ejemplo, no tengan datos o que no sean relevantes para nuestro analisis. Para ello utilizamos el siguiente metodo:
* `df.dropna(subset=['columna1', 'columna2'], inplace=True)`: Este método se utiliza para eliminar columnas específicas de un DataFrame de pandas que no tengan datos relevantes o sean NaN.

In [9]:
df.drop(columns=["id-mapa"], inplace=True)
df.head()

,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,2019,enero,LUN,2019-01-28,8.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630835.0,-58391528.0,1
1,2019,marzo,LUN,2019-03-04,11.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34628442.0,-58391876.0,1
2,2019,abril,MIE,2019-04-10,18.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34630313.0,-58391512.0,1
3,2019,noviembre,LUN,2019-11-18,12.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630163.0,-58391542.0,1
4,2019,abril,LUN,2019-04-01,17.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34629944.0,-58391882.0,1

## Estadisticas descriptivas

Nuestros datos ya están limpios, ahora podemos proceder a realizar un analisis exploratorio de datos. Para ello, utilizaremos el siguiente metodo:
* `df.describe()`: Este método se utiliza para generar estadísticas descriptivas de un DataFrame de pandas. Proporciona un resumen estadístico de las columnas numéricas del DataFrame, incluyendo medidas como la media, la desviación estándar, los cuartiles y los valores mínimo y máximo.

### ¿Qué hace df.describe()?

Al aplicar df.describe() a un DataFrame, obtendrás una tabla resumen que incluye las siguientes estadísticas para cada columna numérica:

* count: El número de valores no nulos.
* mean: La media (promedio) de los valores.
* std: La desviación estándar de los valores.
* min: El valor mínimo.
* 25% (o quantile 0.25): El primer cuartil.
* 50% (o quantile 0.50): La mediana (segundo cuartil).
* 75% (o quantile 0.75): El tercer cuartil.
* max: El valor máximo.

In [18]:
#Obtenemos estatidsticas de nuestro df
# print(df.describe())
df['comuna'].unique()

array([10,  9, 11, 12, 15,  7,  8, 13,  6, 14,  5,  4,  0,  2,  3,  1])

Crearemos una columna nueva para obtener el total de las ventas y modificaremos la columna fecha para convertirla a tipo `datetime`

In [10]:
df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce')
df.head()

,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,2019,enero,LUN,2019-01-28,8.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630835.0,-58391528.0,1
1,2019,marzo,LUN,2019-03-04,11.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34628442.0,-58391876.0,1
2,2019,abril,MIE,2019-04-10,18.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34630313.0,-58391512.0,1
3,2019,noviembre,LUN,2019-11-18,12.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630163.0,-58391542.0,1
4,2019,abril,LUN,2019-04-01,17.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34629944.0,-58391882.0,1

In [12]:
# Convertir abreviaturas de día a número (LUN=0, MAR=1, etc.)
dia_mapping = {'LUN': 0, 'MAR': 1, 'MIE': 2, 'JUE': 3, 'VIE': 4, 'SAB': 5, 'DOM': 6}
df['dia_semana_num'] = df['dia'].map(dia_mapping)

# Crear columna que indique si es día laboral o fin de semana
df['tipo_dia'] = df['dia_semana_num'].apply(lambda x: 'Fin de semana' if x >= 5 else 'Laboral')

# Mapear mes a trimestre
mes_a_trimestre = {
    'enero': 1, 'febrero': 1, 'marzo': 1,
    'abril': 2, 'mayo': 2, 'junio': 2,
    'julio': 3, 'agosto': 3, 'septiembre': 3,
    'octubre': 4, 'noviembre': 4, 'diciembre': 4
}
df['trimestre'] = df['mes'].map(mes_a_trimestre)

# Convertir las columnas 'latitud' y 'longitud' a tipo numérico
df['latitud'] = pd.to_numeric(df['latitud'], errors='coerce')
df['longitud'] = pd.to_numeric(df['longitud'], errors='coerce')

# Función para normalizar coordenadas de Buenos Aires de manera inteligente
def normalizar_coordenadas(df):
    """
    Normaliza las coordenadas de Buenos Aires detectando automáticamente el formato
    y aplicando la transformación adecuada.
    """
    # Crear copias para no modificar las columnas originales
    df['latitud_norm'] = pd.to_numeric(df['latitud'], errors='coerce')
    df['longitud_norm'] = pd.to_numeric(df['longitud'], errors='coerce')
    
    # Detectar escala de las coordenadas
    lat_abs_median = df['latitud_norm'].abs().median()
    lon_abs_median = df['longitud_norm'].abs().median()
    
    print(f"Escala detectada - Latitud: {lat_abs_median}, Longitud: {lon_abs_median}")
    
    # Aplicar transformación según la escala detectada
    # Buenos Aires está aproximadamente en: Lat -34.6, Lon -58.4
    
    # Para latitud
    if lat_abs_median > 1e10:  # Valores extremadamente grandes (ej: -3.461767e+10)
        df['latitud_norm'] = df['latitud_norm'] / 1e9
    elif lat_abs_median > 1e6:  # Valores muy grandes (ej: -34617670)
        df['latitud_norm'] = df['latitud_norm'] / 1e6
    elif lat_abs_median > 1e3:  # Valores grandes (ej: -34617)
        df['latitud_norm'] = df['latitud_norm'] / 1e3
    
    # Para longitud
    if lon_abs_median > 1e10:  # Valores extremadamente grandes
        df['longitud_norm'] = df['longitud_norm'] / 1e9
    elif lon_abs_median > 1e6:  # Valores muy grandes
        df['longitud_norm'] = df['longitud_norm'] / 1e6
    elif lon_abs_median > 1e3:  # Valores grandes
        df['longitud_norm'] = df['longitud_norm'] / 1e3
    
    # Filtrar solo coordenadas en el rango aproximado de Buenos Aires
    df_filtrado = df.copy()
    df_filtrado = df_filtrado[
        (df_filtrado['latitud_norm'] > -40) & (df_filtrado['latitud_norm'] < -30) &
        (df_filtrado['longitud_norm'] > -65) & (df_filtrado['longitud_norm'] < -55)
    ]
    
    # Si después de la normalización no hay suficientes puntos válidos, ajustar la escala
    if len(df_filtrado) < len(df) * 0.1:  # Si se pierden más del 90% de los datos
        print("Ajustando escala debido a pocos puntos válidos...")
        # Intentar con otra escala para latitud
        for factor in [1e2, 1e4, 1e5, 1e7, 1e8]:
            df['latitud_norm'] = pd.to_numeric(df['latitud'], errors='coerce') / factor
            df['longitud_norm'] = pd.to_numeric(df['longitud'], errors='coerce') / factor
            
            df_test = df[
                (df['latitud_norm'] > -40) & (df['latitud_norm'] < -30) &
                (df['longitud_norm'] > -65) & (df['longitud_norm'] < -55)
            ]
            
            if len(df_test) > len(df) * 0.5:  # Si recuperamos al menos el 50% de los datos
                print(f"Nueva escala encontrada: {factor}")
                break
    
    return df

# Aplicar la función a tu DataFrame
df = normalizar_coordenadas(df)

# Verificar resultados
print(f"Coordenadas normalizadas - Rango de latitud: {df['latitud_norm'].min()} a {df['latitud_norm'].max()}")
print(f"Coordenadas normalizadas - Rango de longitud: {df['longitud_norm'].min()} a {df['longitud_norm'].max()}")

# Rellenar valores nulos primero y luego convertir

# df['dia_semana_num'] = df['dia_semana_num'].fillna(0).astype(int)
# df['trimestre'] = df['trimestre'].fillna(0).astype(int)
# df['franja'] = df['franja'].fillna(0).astype(int)

# # df.dropna(subset=["id-mapa"], inplace=True)

#creamos un nuevo csv con nuestros df limpio
df.to_csv("datasets_delitos_2019_2023_limpio.csv", index=False)
df

Escala detectada - Latitud: 34598564.5, Longitud: 58406035.0
Coordenadas normalizadas - Rango de latitud: -34700000000.0 a 3.5e-05
Coordenadas normalizadas - Rango de longitud: -58600000000.0 a 5.840982

,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad,dia_semana_num,tipo_dia,trimestre,latitud_norm,longitud_norm
0,2019,enero,LUN,2019-01-28,8.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630835.0,-58391528.0,1,0.0,Laboral,1.0,-34.630835,-58.391528
1,2019,marzo,LUN,2019-03-04,11.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34628442.0,-58391876.0,1,0.0,Laboral,1.0,-34.628442,-58.391876
2,2019,abril,MIE,2019-04-10,18.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34630313.0,-58391512.0,1,2.0,Laboral,2.0,-34.630313,-58.391512
3,2019,noviembre,LUN,2019-11-18,12.0,Hurto,Hurto total,NO,NO,PARQUE PATRICIOS,4.0,-34630163.0,-58391542.0,1,0.0,Laboral,4.0,-34.630163,-58.391542
4,2019,abril,LUN,2019-04-01,17.0,Robo,Robo total,NO,NO,PARQUE PATRICIOS,4.0,-34629944.0,-58391882.0,1,0.0,Laboral,2.0,-34.629944,-58.391882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646035,2023,diciembre,VIE,2023-12-01,14.0,Homicidios,Homicidio Doloso,NO,NO,PARQUE CHACABUCO,7,0.0,0.0,1,4.0,Laboral,4.0,0.000000,0.000000
646036,2023,diciembre,DOM,2023-12-17,23.0,Homicidios,Homicidio Doloso,NO,NO,MONSERRAT,1,0.0,0.0,1,6.0,Fin de semana,4.0,0.000000,0.000000
646037,2023,diciembre,DOM,2023-12-24,22.0,Homicidios,Homicidio Doloso,NO,NO,VILLA CRESPO,15,0.0,0.0,1,6.0,Fin de semana,4.0,0.000000,0.000000
646038,2023,diciembre,DOM,2023-12-24,17.0,Homicidios,Homicidio Doloso,NO,NO,BALVANERA,3,0.0,0.0,1,6.0,Fin de semana,4.0,0.000000,0.000000
646039,2023,diciembre,DOM,2023-12-31,7.0,Homicidios,Homicidio Doloso,NO,NO,FLORES,7,0.0,0.0,1,6.0,Fin de semana,4.0,0.000000,0.000000

## Visualización de datos con Matplotlib
Ahora que tenemos nuestros datos limpios y hemos realizado un análisis exploratorio, podemos proceder a visualizar nuestros datos. Para ello, utilizaremos la libreria Matplotlib.

In [ ]:
#importamos matplolib, en especifico pyplot y le asignamos el alias plt
import matplotlib.pyplot as plt

Vamos a crear una visualizacion, para ello, necesitamos utilizar los siguientes metodos:
* `plt.plot(x, y)`: Este método se utiliza para crear un gráfico de líneas en Matplotlib. Acepta dos listas o arrays como argumentos: x e y, que representan las coordenadas de los puntos a graficar.
* `plt.title('titulo')`: Este método se utiliza para establecer el título del gráfico.
* `plt.xlabel('nombre_x')`: Este método se utiliza para establecer la etiqueta del eje x.
* `plt.ylabel('nombre_y')`: Este método se utiliza para establecer la etiqueta del eje y.
* `plt.show()`: Este método se utiliza para mostrar el gráfico en la pantalla. Es el último paso para visualizar el gráfico que has creado.
* `plt.savefig('nombre_grafico.png')`: Este método se utiliza para guardar el gráfico en un archivo de imagen. Puedes especificar el nombre del archivo y la extensión (por ejemplo, .png, .jpg, .pdf, etc.). Si no se especifica la ruta completa, el archivo se guardará en el directorio de trabajo actual.

In [ ]:
#Agrupamos los datos con df.grupby
ventas_por_dia = df.groupby('fecha')['total'].sum()
ventas_por_cantidad = df.groupby('fecha')['cantidad'].sum()

#tamaño de la figura
plt.figure(figsize=(10,5))
#titulo
plt.title("Ventas totales por día")
#pasamos los valores x, y
plt.plot(ventas_por_dia.index, ventas_por_dia.values)
plt.xlabel("Cantidad de productos")
plt.ylabel("Total vendido por dia")
plt.xticks(rotation=20)
plt.grid()
plt.show()

In [ ]:
ventas_por_cantidad = df.groupby('fecha')['cantidad'].sum()

#tamaño de la figura
plt.figure(figsize=(10,5))
#titulo
plt.title("Ventas totales por día")
#pasamos los valores x, y
plt.plot(ventas_por_cantidad.index, ventas_por_cantidad.values)
plt.xlabel("Cantidad de productos")
plt.ylabel("Total vendido por dia")
plt.xticks(rotation=20)
plt.grid()
plt.show()